name: Release Asset

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Assets
        uses: actions/checkout@v2
        run: |
          set -x
          bash scorm.all.sh
          assets=()
          for asset in ./release/*.zip; do
            assets+=(-a $asset)
          done
          tag_name=${GITHUB_REF##*/}
          hub release edit ${assets[@]} -m $tag_name $tag_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}