name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: External Hyperlinks test
        run: php tests/external_links.php *.md

      - name: Internal & External Resources test
        run: php tests/resource_links.php *.md *.html

      - name: Internal Resources Usage test
        run: php tests/resource_usage.php download/ *.md *.js *.css
